[tool.poetry]
name = "django-basic"
version = "0.1.0"
description = ""
authors = ["lev <levbezrukov@bk.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.3"
django-stubs = "^1.10.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
